name: Bump-Latest-Client

on:
  issue_comment:
    types: [created]
jobs:
  rebase:
    name: Bump submodule
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the latest code
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0
      - name: View context attributes
        uses: actions/github-script@v3
        with:
          script: console.log(context)
